---
include:
  - project: 'custom/gitlab-templates'
    ref: main
    file: docker.yaml

  - project: 'custom/gitlab-templates'
    ref: main
    file: kubernetes.yaml

  - project: 'custom/gitlab-templates'
    ref: main
    file: notifications.yaml

stages:
  - notify-start
  - test
  - build
  - deploy
  - notify-end

variables:
  IMG_NAME: custom-api
  CLUSTER_NAME: "development"
  CUSTOM_BRANCH_DEPLOY: "do-not-change." #Workaround to prevent accidental branch deploy

test:
  image: node:16
  stage: test
  script:
    - npm ic
    - npm run test:ci
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  coverage: '/Lines \W+: \d+.\d+% \( /'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build_docker:
  stage: build
  extends:
    - .docker_job
  tags:
    - saas-linux-medium-amd64
  script:
    - docker build -t ${AWS_REGISTRY}/${IMG_NAME}:${TAG} -f Dockerfile ./
    - docker push ${AWS_REGISTRY}/${IMG_NAME}:${TAG}
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'  #prod
      when: on_success
      variables:
        TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'  #develop
      when: on_success
      variables:
        TAG: "develop"
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\d+$/'  #rc
      when: on_success
      variables:
        TAG: $CI_COMMIT_TAG
    - if: '$CUSTOM_BRANCH_DEPLOY == $CI_COMMIT_BRANCH'  #Custom branch deploy. Set $CUSTOM_BRANCH_DEPLOY variable in gitlab to the branch you want to be deployed.
      when: on_success
      variables:
        TAG: $CUSTOM_BRANCH_DEPLOY

helm_deploy:
  variables:
    RELEASE_NAME: "api"
  extends:
    - .kubernetes_auth
    - .helm_deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\d+$/'  #rc
      when: on_success
      variables:
        ENVIRONMENT: "rc"
        IMAGE_TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == "develop"'  #develop
      when: on_success
      variables:
        ENVIRONMENT: "development"
        IMAGE_TAG: "develop"
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'  #prod
      when: on_success
      variables:
        ENVIRONMENT: "production"
        IMAGE_TAG: $CI_COMMIT_TAG
        CLUSTER_NAME: "production"
    - if: '$CUSTOM_BRANCH_DEPLOY == $CI_COMMIT_BRANCH'  #Custom branch deploy. 
      when: on_success
      variables:
        ENVIRONMENT: "development"
        IMAGE_TAG: $CUSTOM_BRANCH_DEPLOY